# Generated by Django 3.2.11 on 2024-04-25 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_approvals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='firtname',
            new_name='firtsname',
        ),
    ]
