# Generated by Django 3.2.11 on 2024-04-25 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_firtname_approvals_firtsname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvals',
            old_name='firtsname',
            new_name='firstname',
        ),
    ]
