# Generated by Django 4.2.13 on 2024-05-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_coapplicantincome_approvals_coapplicatincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_block_num', models.IntegerField(blank=True, default=0, null=True)),
                ('shop_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('item_price', models.FloatField()),
                ('item_cnt_day', models.FloatField(blank=True, default=0, null=True)),
                ('name', models.CharField(max_length=255)),
                ('predictions', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-date_block_num'],
            },
        ),
        migrations.DeleteModel(
            name='Approvals',
        ),
    ]
