# Generated by Django 4.2.13 on 2024-05-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_data_delete_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_block_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='item_cnt_day',
            field=models.FloatField(),
        ),
    ]
