# Generated by Django 5.0.6 on 2024-05-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payment_vnpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_vnpay',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
