# Generated by Django 5.0.6 on 2024-05-21 10:02

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_payment_vnpay_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='email',
            field=models.CharField(default=1, max_length=100, validators=[app.models.validate_email]),
            preserve_default=False,
        ),
    ]
