# Generated by Django 5.0.6 on 2024-05-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_customer_shippingaddress_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='name',
            new_name='user',
        ),
    ]
